model:
  loss: "mse"
  num_boost_round: 1200
  early_stopping_rounds: 80
  params:
    boosting_type: "gbdt"
    learning_rate: 0.05
    max_depth: -1
    num_leaves: 64
    feature_fraction: 0.8
    bagging_fraction: 0.8
    bagging_freq: 5
    lambda_l1: 0.0
    lambda_l2: 1.0
    min_data_in_leaf: 50
    verbosity: -1


